language: csharp
solution: tenancycore.sln
os: linux
dotnet: "2.1.1"
mono: none
install: 
  - ls /home/travis/build/Dongata/tenancycore/src/
  - ls /home/travis/build/Dongata/tenancycore/src/core/
  - ls /home/travis/build/Dongata/tenancycore/src/models/
  - ls /home/travis/build/Dongata/tenancycore/src/extensions/
  - dotnet restore
script:
  - dotnet build --configuration release
  - dotnet test core.tests/core.tests.csproj --configuration release
  - dotnet test extensions.tests/Extensions.tests.csproj --configuration release
  - dotnet test models.tests/models.tests.csproj --configuration release